2017-12-09 15:29:45,353 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 15:38:14,381 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 15:54:35,938 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 15:54:48,607 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 16:08:22,796 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 16:09:45,465 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 18:08:28,215 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 18:09:05,138 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 18:10:31,753 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 18:10:53,913 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 18:30:53,719 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 23:05:15,636 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 23:16:34,953 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 23:22:47,780 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 23:28:22,532 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-09 23:28:36,339 ERROR: Exception on /user/krk1 [GET] [in /Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/karthikrk/Desktop/Courses/flask-app/app/routes.py", line 79, in user
    page = request.agrs.get('page', 1, type=int)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'agrs'
2017-12-09 23:28:38,481 ERROR: Exception on /user/krk1 [GET] [in /Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/karthikrk/Desktop/Courses/flask-app/app/routes.py", line 79, in user
    page = request.agrs.get('page', 1, type=int)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'agrs'
2017-12-09 23:29:10,332 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:47]
2017-12-10 09:51:51,742 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:49]
2017-12-10 09:51:54,493 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:49]
2017-12-10 21:05:49,467 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:49]
2017-12-10 21:06:27,480 ERROR: Exception on /reset_password_request [POST] [in /Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karthikrk/Desktop/Courses/flask-app/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karthikrk/Desktop/Courses/flask-app/app/routes.py", line 156, in reset_password_request
    send_password_reset_email(user)
  File "/Users/karthikrk/Desktop/Courses/flask-app/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2017-12-10 21:08:52,226 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:49]
2017-12-10 21:10:59,055 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:49]
2017-12-10 21:25:29,340 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:51]
2017-12-11 21:07:23,273 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:51]
2017-12-11 21:21:08,409 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:53]
2017-12-12 17:54:23,079 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:55]
2017-12-12 17:55:19,596 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:55]
2017-12-12 18:22:43,691 INFO: Flask App startup [in /Users/karthikrk/Desktop/Courses/flask-app/app/__init__.py:55]
